### ISSUE TITLE
[Bug / FR] Cannot be installed with BRAT

### ISSUE THREAD

**Issue by StefanoRausch** [gapmiss/livecodes-for-obsidian#1]
![image](https://github.com/gapmiss/livecodes-for-obsidian/assets/1460531/39f57852-70c0-4c72-abc3-994520b3456e)

I am looking forward to manage the beta plugin via BRAT. 😉

**Comment by gapmiss** [comment]
Good catch. The version number was incorrect in the manifest.json. It is fixed now and I have confirmed that the plugin is installable via BRAT. Thanks again.

**Comment by StefanoRausch** [comment]
I can confirm and thank you!

**Comment by gapmiss** [comment]
Have added BRAT instructions to README also.

###### Install via BRAT (Beta Reviewer's Auto-update Tool)

1. Ensure [BRAT](https://github.com/TfTHacker/obsidian42-brat) is installed
2. Trigger the command `Obsidian42 - BRAT: Add a beta plugin for testing` 
3. Enter this repository, `gapmiss/livecodes-for-obsidian`
4. Enable *Livecodes* plugin in community plugin list
