### ISSUE TITLE
[Bug] The template folder does not exist

### ISSUE THREAD

**Issue by StefanoRausch** [gapmiss/livecodes-for-obsidian#2]
![image](https://github.com/gapmiss/livecodes-for-obsidian/assets/1460531/29e79b52-db49-47b6-a943-f81529514b93)

**Comment by gapmiss** [comment]
Thank you Stefano,

Templates are here: https://github.com/gapmiss/livecodes-for-obsidian/tree/master/templates

I will fix the README to reflect this correct URL.
